data = [



        {

            "question": "Who was the first person to walk on the Moon?",

            "options": ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"],

            "answer": "Neil Armstrong",

        },

        {

            "question": "Which space agency launched the Hubble Space Telescope?",

            "options": ["NASA", "ESA", "Roscosmos", "ISRO"],

            "answer": "NASA",

        },

        {

            "question": "What is the name of SpaceX’s reusable rocket?",

            "options": ["Falcon 9", "Starship", "Atlas V", "Delta IV"],

            "answer": "Falcon 9",

        },

        {

            "question": "Which planet did the rover Perseverance land on?",

            "options": ["Mars", "Venus", "Jupiter", "Saturn"],

            "answer": "Mars",

        },

        {

            "question": "What does ISS stand for?",

            "options": [

                "International Space Station",

                "Interstellar Space Ship",

                "Independent Space Satellite",

                "Internal Space System"

            ],

            "answer": "International Space Station",

        },

        {

            "question": "Who was the first human in space?",

            "options": ["Yuri Gagarin", "Neil Armstrong", "Alan Shepard", "John Glenn"],

            "answer": "Yuri Gagarin",

        },

        {

            "question": "Which country was the first to send a satellite into space?",

            "options": ["Soviet Union", "USA", "China", "France"],

            "answer": "Soviet Union",

        },

        {

            "question": "What kind of fuel do most rockets use?",

            "options": ["Liquid hydrogen and oxygen", "Gasoline", "Diesel", "Electric batteries"],

            "answer": "Liquid hydrogen and oxygen",

        },

        {

            "question": "Which spacecraft was the first to land humans on the Moon?",

            "options": ["Apollo 11", "Sputnik 1", "Challenger", "Voyager 1"],

            "answer": "Apollo 11",

        },

        {

            "question": "What is the primary purpose of a spacesuit?",

            "options": [

                "To protect astronauts from the vacuum of space",

                "To improve communication",

                "To generate oxygen",

                "To increase speed"

            ],

            "answer": "To protect astronauts from the vacuum of space",

        },





        {"question": "The Moon has no atmosphere.", "answer": "True"},

        {"question": "Mars is closer to the Sun than Earth.", "answer": "False"},

        {"question": "The Hubble Space Telescope orbits the Earth.", "answer": "True"},

        {"question": "SpaceX was founded by Jeff Bezos.", "answer": "False"},

        {"question": "The ISS orbits Earth approximately every 90 minutes.", "answer": "True"},

        {"question": "Apollo 13 successfully landed on the Moon.", "answer": "False"},

        {"question": "Gravity is weaker on the Moon than on Earth.", "answer": "True"},

        {"question": "Venus is known as the ‘Red Planet.’", "answer": "False"},

        {"question": "The Mars rover Curiosity is still operational as of 2025.", "answer": "True"},

        {"question": "Astronauts experience weightlessness in orbit.", "answer": "True"},





        {"question": "What is a black hole?", "answer": "A region in space with gravity so strong that nothing can escape it"},

        {"question": "Name the first artificial satellite sent into space.", "answer": "Sputnik 1"},

        {"question": "What is microgravity?", "answer": "A condition of very weak gravity experienced in orbit"},

        {"question": "Who was the first American astronaut to orbit the Earth?", "answer": "John Glenn"},

        {"question": "What is the purpose of the Mars rovers?", "answer": "To explore Mars’ surface and gather data"},

        {"question": "Name a major space telescope besides Hubble.", "answer": "James Webb Space Telescope"},

        {"question": "What is the main component of rocket propulsion?", "answer": "Thrust generated by expelling gases"},

        {"question": "What does EVA stand for in space missions?", "answer": "Extravehicular Activity (spacewalk)"},

        {"question": "Why do astronauts need to exercise in space?", "answer": "To prevent muscle and bone loss due to weightlessness"},

        {"question": "What is the significance of the Voyager missions?", "answer": "Exploring outer planets and interstellar space"},





        {"question": "What year did the Apollo 11 Moon landing occur?", "answer": "1969"},

        {"question": "Which planet is known as the ‘Red Planet’?", "answer": "Mars"},

        {"question": "What is NASA?", "answer": "National Aeronautics and Space Administration"},

        {"question": "Name the first woman in space.", "answer": "Valentina Tereshkova"},

        {"question": "What does 'ROSCOSMOS' refer to?", "answer": "Russian space agency"},

        {"question": "What is the name of the first reusable spacecraft?", "answer": "Space Shuttle"},

        {"question": "Name the space probe that took the first close-up images of Pluto.", "answer": "New Horizons"},

        {"question": "What is the unit used to measure distance in space?", "answer": "Light-year"},

        {"question": "What is the main gas used in pressurized spacecraft cabins?", "answer": "Oxygen"},

        {"question": "Which mission was the first to return samples from an asteroid?", "answer": "Hayabusa"},


]


