QUIZZES_V2_COLLECTION = "quizzes_v2"
FOLDERS_V2_COLLECTION = "folders_v2"
FOLDER_ITEMS_V2_COLLECTION = "folder_items_v2"
SAVED_QUIZZES_V2_COLLECTION = "saved_quizzes_v2"
QUIZ_HISTORY_V2_COLLECTION = "quiz_history_v2"

QUIZ_SCHEMA_VERSION = 1
